// <auto-generated />
using System;
using Kztek_Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kztek_Data.Migrations
{
    [DbContext(typeof(Kztek_Entities))]
    [Migration("20190916141834_k1")]
    partial class k1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Kztek_Model.Models.SY_Map_Role_Menu", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MenuId")
                        .IsRequired();

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SY_Map_Role_Menu");
                });

            modelBuilder.Entity("Kztek_Model.Models.SY_Map_User_Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SY_Map_User_Role");
                });

            modelBuilder.Entity("Kztek_Model.Models.SY_MenuFunction", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionName");

                    b.Property<short>("Active")
                        .HasColumnName("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Breadcrumb");

                    b.Property<string>("ControllerName");

                    b.Property<DateTime>("DateCreated");

                    b.Property<int?>("Dept");

                    b.Property<string>("Icon");

                    b.Property<string>("MenuName")
                        .IsRequired();

                    b.Property<string>("MenuType");

                    b.Property<string>("ParentId");

                    b.Property<int>("SortOrder");

                    b.HasKey("Id");

                    b.ToTable("SY_MenuFunction");
                });

            modelBuilder.Entity("Kztek_Model.Models.SY_Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("Active")
                        .HasColumnName("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description");

                    b.Property<string>("RoleName");

                    b.HasKey("Id");

                    b.ToTable("SY_Role");
                });

            modelBuilder.Entity("Kztek_Model.Models.SY_User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("Active")
                        .HasColumnName("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Avatar");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password");

                    b.Property<string>("PasswordSalat");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.Property<short>("isAdmin")
                        .HasColumnName("isAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SY_User");
                });
#pragma warning restore 612, 618
        }
    }
}
